spring:
  data:
    mongodb:
      database: orbisv2production
      uri: mongodb://localhost:27017/?retryWrites=true

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
            repository:
              query: DEBUG

app:
  polygon-calculation:
    enable: true
    test-controller-enable: false
    delay-in-sec: 1
    start-page: 0
    page-size: 3